services:
  node:
    image: limehome/backend-challenge-typescript
    build: .
    user: node
    userns_mode: keep-id
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - .:/home/node/app:z
